server.port=8081

spring.datasource.url=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=change-this-secret-for-prod
jwt.expiration=3600000

management.endpoints.web.exposure.include=health,info,metrics,prometheus

keycloak.base-url=${KEYCLOAK_BASE_URL:http://keycloak:8080}
keycloak.realm=${KEYCLOAK_REALM:medicalsystem}
keycloak.admin-realm=${KEYCLOAK_ADMIN_REALM:master}
keycloak.admin-client-id=${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
keycloak.admin-username=${KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD:admin}
