spring.application.name=records-billing-service
server.port=8085
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/medicalsystem}
spring.data.mongodb.auto-index-creation=true
appointments.service.base-url=${APPOINTMENTS_SERVICE_BASE_URL:http://appointments-service:8083/api}

# Actuator / Metrics
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# JWT secret (for local testing; use secure secret in production)

# Use Keycloak JWKS for validating tokens in resource server
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URI:http://keycloak:8080/realms/medicalsystem/protocol/openid-connect/certs}
