spring.application.name=MedicalSystem
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/medicalsystem}
spring.data.mongodb.auto-index-creation=true
app.admin.name=System Administrator
app.admin.email=admin@medicalsystem.com
app.admin.password=Admin@123
