server.port=8083

spring.data.mongodb.uri=${MONGODB_URI:mongodb://mongodb:27017/medicalsystem}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

logging.level.org.springframework=INFO

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URI:http://keycloak:8080/realms/medicalsystem/protocol/openid-connect/certs}
